language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run copy-utils
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: V3fabo9YfzfOFVl1qqgi/4Y98hDSyr563kgkCBkt99A6Uc7A0W4HxCkrxCWgMEx6it/at9obFneRmiTWHisoOaW9FnWv6fXlwMTKvMnaT4dcASiF9fRn4IKUlUWZNdF70lgK18fbiXPTOM4hbEqSeyePFvBGL+1K66BujfgGlNH6SvKJi0eY0i9yX391/PBewGuQjope/uOn6NXY5MuGUaBJdDCeSAvzO8G68PUZNixwJoh43JKW26i0jwyOzdEFh8FiUXcGkx6xHrxPby2iwSWxF/7CVKaXfKj+yWhAvnwLpvdtVoCWOAiUQYRp4W/Ajcliz2GKS9G3BcQpwzpBtABkge/FCFik7wRYDLeYMTuLMeADFvNy7U6APxaarkavp7cnGkHr4/aV2U4B9h1yWJzWwgRyquYk8hnmf0HFJ6PMkCnF1Q5F6QZyVIbKwURCd7Ura4DJC2Ys/QUoPg2icteEKq1CzjTvJh/DgpObM/7PORC4zqipNkgfASQlxdcmS61cgP7Ev7u0f600yNGlVKqEndRfTEgA2XqSVYOkoNG6OUaKEuYyvqPI1G3McTjYlaT3UHI1hr6ym1aixCp1nh3Gu8/SO18puFl90PKEXNZ4Q5i/7Q1QNfrjjP+i1JiF45qxct+VCjVmmRpYeJlbkZgVS+qkrpxL/rJERBiBbvE=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
  - secure: OE5PzQSgXuMBrM1Gb9LS5AQOF/HWfWfA2TK8zVr2DgSbaNojpd+D0O3NIQRygxACvhNA4OMVu33H9L6+Y3dvboxg1UCiXvzIl1HRfp9alqG54Y93ie4f7HYYdyD03pc+voD09CTErRfzCbD1pDLeUxS6w0Mm7Gv6I1ZI0Syx8nrj3cL6ZlSKS4BI5WAeM5a4m2gdwy598ajADj80Pg2T9uHcQUtiEcaoTgSH2V59T5I55St4D2WHPNsXYuuLtRKUBcp209vEDzqUdaUnavceNpzAQnKlU19FPZMLcNkLv78BZg5RmpBi81UQnQzqyUMW8Lhp7l4Im4lPUN1grMuwQ0q9e4RH9M26XwI5MlfUZTXvQZJl7Dpqk53WrMtnqoGs8hE514Ie9mY4dh/8PwcKJ6cCZuDp13VldG0+jPcKYZnl4i9X8XWci6CwVBW0FMaPTNZdt8zZJBeaWkxHHeUBqRJc3B54DPVJiSWqC459QZtl32o/UmhxzfG9dIA+hbn4LFrx65sg8/2J/+yWobPs14k//mBWK9ub+hlTvQW9TiUkTvB0Vnjz0XE5+tVustYM1GloTky3Id0bHqo2ecXAkk5riIAP/kkDi8wu5SCw7QoFl6JYTb0mkqv2iHKo8Il4omA3dvIMuh8Ao3BFvXD+Re11wqBLEe1ByABHx1J38Dw=
