language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run copy-utils
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: V3fabo9YfzfOFVl1qqgi/4Y98hDSyr563kgkCBkt99A6Uc7A0W4HxCkrxCWgMEx6it/at9obFneRmiTWHisoOaW9FnWv6fXlwMTKvMnaT4dcASiF9fRn4IKUlUWZNdF70lgK18fbiXPTOM4hbEqSeyePFvBGL+1K66BujfgGlNH6SvKJi0eY0i9yX391/PBewGuQjope/uOn6NXY5MuGUaBJdDCeSAvzO8G68PUZNixwJoh43JKW26i0jwyOzdEFh8FiUXcGkx6xHrxPby2iwSWxF/7CVKaXfKj+yWhAvnwLpvdtVoCWOAiUQYRp4W/Ajcliz2GKS9G3BcQpwzpBtABkge/FCFik7wRYDLeYMTuLMeADFvNy7U6APxaarkavp7cnGkHr4/aV2U4B9h1yWJzWwgRyquYk8hnmf0HFJ6PMkCnF1Q5F6QZyVIbKwURCd7Ura4DJC2Ys/QUoPg2icteEKq1CzjTvJh/DgpObM/7PORC4zqipNkgfASQlxdcmS61cgP7Ev7u0f600yNGlVKqEndRfTEgA2XqSVYOkoNG6OUaKEuYyvqPI1G3McTjYlaT3UHI1hr6ym1aixCp1nh3Gu8/SO18puFl90PKEXNZ4Q5i/7Q1QNfrjjP+i1JiF45qxct+VCjVmmRpYeJlbkZgVS+qkrpxL/rJERBiBbvE=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: o3fw+zSFJMnmM1c2kJJ4zXlPTYO6Zhr4jeQpXKYDhwatO7PC15IyRv7lfCRvVgrPAZqxE2RRc7+0xd/FEpkO8SI+1U6WD/ZD4MIa7TlcrnTqN3hyLL0Pxu1koZVk9rTohCAcnp1tQek5xUIKO5H7VfhHRA5l4rPYnWyotV/oYciYnUpOd7/ZwZYkAYMDd/3uhI04q/gV0P+xQCPImUbkU/HwOE/drBdq3j1sWO6QjkwPN2F94+o1HJs9maixz2Z/miZamjT2xX4aoP8//dqRWA+2Dji4Jj7y7biVdV9iHljnPV4ycXhSs1DmnMICpS0QD/7mRshaYJPXRgIqIxwCyWtyoQhsw7KU6tGUWDp/Ys8v4NXcCgZotv62KrcgXfbxGtlteOvdB9dNKvJFeEQd2x09z4p1AQRseRkjEZ1Ua8JJMzFuaCawHLtk9Ouu5o4TONtDPjt2f/n7xukDSeDZDVjNYNuDIApUbRC+LdqIMOa7RTKnNcYSly6qW27e3HDvIHOqV0Vx3ar1x+zXpz7YUR7KpiFrj5QyCKjisT+ZoruAHlNnkM/1+SblPEJci8UR+Vu/mdI07MTVo/CwAfrCMl9V8hX2lcNuUyqGYsZM9VPbgg80d21t3HuUOr3j1pyf7fQxSPSNZsF9bG3gqun1g/KjaEgvceumz/2jqTCVb/E=
